### ISSUE TITLE
Making grunt-hub return an error if one of the subtask produced an error ?

### ISSUE THREAD

**Issue by warpdesign** [shama/grunt-hub#51]
I have defined a hub with two Gruntfile:

  'all': {
    src: ['engine/Gruntfile.js', 'editor/Gruntfile.js'],
    options: {
      concurrent: 1
    }
  }

When I run `grunt hub:all:test` it runs the tests for the first Gruntfile, then tests for the second project. The problem is that grunt:hub will return success even though one of the Gruntfile executed returned an error. Is there a way to return an error if one of the Gruntfile executed returned an error?

**Comment by shama** [comment]
[It should here](https://github.com/shama/grunt-hub/blob/master/tasks/hub.js#L79) if an error occurs. Unless an error isn't being written to stderr or the code there isn't right.

**Comment by warpdesign** [comment]
My mistake: I was using grunt-continue which forces the process to go on even though an error has been encountered. Disabling it makes grunt-hub returns an error as expected.
