### ISSUE TITLE
Run npm install for each project

### ISSUE THREAD

**Issue by CupOfTea696** [shama/grunt-hub#54]
Would it be possible to add an option to run `npm install` in each project before running grunt?

**Comment by shama** [comment]
Yes run a task that runs shell commands, such as: https://github.com/sindresorhus/grunt-shell Or use `require('npm')` directly with your own task.

This task just runs other tasks across multiple Grunt projects.

**Comment by humhann** [comment]
You could add this to package.json of your root project:

```
"scripts": {
    ...
    "install": "(cd sub/project-a && npm install) && (cd sub/project-b/ && npm install)"
  },
```

In this case, all three are going to be installed when running `npm install` in root.
