### ISSUE TITLE
New release including the recent upgrade to lodash 4.17.5

### ISSUE THREAD

**Issue by ChristianOlsson** [shama/grunt-hub#57]
npm audit is complaining about grunt-hub having a dependency on lodash 2.4.1. The required changes have already been merged to master with   #56 

It would be great if we could have a new release including these changes.

**Comment by HamletDRC** [comment]
Any idea when a release might come?

**Comment by shama** [comment]
Published as `1.0.0`. Thanks!

**Comment by ChristianOlsson** [comment]
Thank you very much!
